---
title: "Conditional PMR Code"
author: "Adina Zhang"
date: "June 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Try conditional PMR on sample dataset of 5000 observations

```{r}
# Load datasets
mort65plus = read_csv("./mort17_65plus.csv") %>% mutate(id = row_number())
icd10_df = read_csv("icd10_hierarchy.csv")

set.seed(1)

# Simplify to a test dataset
sample_df = mort65plus %>% 
  sample_n(5000) %>% 
  select(X1, icd10, ra2:ra20) %>% 
  rename(id = X1)

# Filter out number of individuals with underlying causes of death == W00-W19 (falls)
sample_fall = sample_df %>% 
  filter(grepl("W", icd10)) %>%
  mutate(number = str_sub(icd10, 2, 3)) %>% 
  filter(number <= 19) %>% select(-number) 

# Tidy fall data
# Filter out icd10 codes were are not interested in
tidy_fall = sample_fall %>%
  gather(key = ra_position, value = ra_value, ra2:ra20) %>% 
  filter(!str_detect(ra_value, "^S"),
         !str_detect(ra_value, "^T0"),
         !str_detect(ra_value, "^T1")) %>% 
  na.omit()

```

```{r}
# Count observed number of pairs among falls
# Count icd10 occurrence among falls
fall_comb = tidy_fall %>%
  select(-icd10, -ra_position) %>% 
  mutate(n = 1) %>%
  spread(ra_value, n, fill = 0) %>% 
  select(-id) %>% 
  {crossprod(as.matrix(.))} %>% 
  replace(lower.tri(., diag = T), NA) %>% 
  reshape2::melt(na.rm = T) %>% 
  arrange(desc(value))
```

```{r}
# Count pairs of icd10 codes among all 65+ adults
sample_tidy = sample_df %>% 
  gather(key = ra_position, value = ra_value, ra2:ra20) %>% 
  na.omit()

sample_comb = sample_tidy %>% 
  select(-icd10, -ra_position) %>% 
  mutate(n = 1) %>% 
  # Filter out any duplicate data for the same person (one person had K729 
  # entered twice)
  distinct(id, ra_value, n) %>% 
  spread(ra_value, n, fill = 0) %>% 
  select(-id) %>% 
  {crossprod(as.matrix(.))} %>% 
  replace(lower.tri(., diag = T), NA) %>% 
  reshape2::melt(na.rm = T) %>% 
  arrange(desc(value))
  
```

```{r}
# Join fall with overall sample counts
# Calculate expected value and PMR
full_join(fall2, sample_comb, by = c("Var1", "Var2")) %>% 
  rename(obs = value.x,
         n = value.y) %>% 
  mutate(prev = n / dim(sample_df)[1],
         exp = prev * dim(sample_fall)[1],
         pmr = obs / exp)
```

## Try conditional pmr on full dataset

```{r}
# Write functions out of previous code
fall_combo = function(data){
  data %>%
  select(-icd10, -ra_position) %>% 
  mutate(n = 1) %>%
  distinct(id, ra_value, n) %>% 
  spread(ra_value, n, fill = 0) %>% 
  select(-id) %>% 
  {crossprod(as.matrix(.))} %>% 
  replace(lower.tri(., diag = T), NA) %>% 
  reshape2::melt(na.rm = T) %>% 
  arrange(desc(value))
}

full_combo = function(data){
  data %>% 
  select(-icd10, -ra_position) %>% 
  mutate(n = 1) %>% 
  # Filter out any duplicate data for the same person (one person had K729 
  # entered twice)
  distinct(id, ra_value, n) %>% 
  spread(ra_value, n, fill = 0) %>% 
  select(-id) %>% 
  {crossprod(as.matrix(.))} %>% 
  replace(lower.tri(., diag = T), NA) %>% 
  reshape2::melt(na.rm = T) %>% 
  arrange(desc(value))
}
```

```{r}
# Prepare datasets for use in functions
# Tidy population data
tidy_pop = mort65plus %>%
  select(id, icd10, ra2:ra20) %>% 
  gather(key = ra_position, value = ra_value, ra2:ra20) %>% 
  na.omit()

# Filter out number of individuals with underlying causes of death == W00-W19 (falls)
falls = mort65plus %>% 
  filter(grepl("W", icd10)) %>%
  mutate(number = str_sub(icd10, 2, 3)) %>% 
  filter(number <= 19) %>% 
  select(id, icd10, ra2:ra20) 

# Tidy fall data
# Filter out icd10 codes were are not interested in
tidy_falls = falls %>%
  gather(key = ra_position, value = ra_value, ra2:ra20) %>% 
  filter(!str_detect(ra_value, "^S"),
         !str_detect(ra_value, "^T0"),
         !str_detect(ra_value, "^T1")) %>% 
  na.omit()
```

```{r}
fall_test = full_combo(tidy_falls)
pop_test = full_combo(tidy_pop)
```

