---
title: "PMR Tables and Figures"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
library(kableExtra)
```

### PAR Table Adjusted for Females (ntotal = 1093067, nfall = 16558)

```{r, include = FALSE}
# Load combined datasets
female = read_csv("./female_combined.csv")
```

```{r, echo = FALSE}
female[1:50,] %>% 
  knitr::kable(booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  add_indent(c(2, 3, 6, 7, 9, 10, 13, 15, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 32, 33, 34, 36, 37, 39, 41, 43, 45, 49))
```

\newpage

```{r, echo = FALSE}
female[51:74,] %>% 
  knitr::kable(booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  add_indent(c(2, 3, 4, 6, 15, 21))
```

\newpage

### PAR Table Adjusted for Males (ntotal = 977304, nfall = 14686)

```{r, include = FALSE}
male = read_csv("./male_combined.csv")
```

```{r, echo = FALSE}
male[1:50,] %>% 
  knitr::kable(booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  add_indent(c(2, 3, 5, 6, 9, 11:17, 20, 22, 23, 26, 28, 29, 32, 
               37, 38, 42, 44, 46, 48, 50))
```

\newpage

```{r, echo = FALSE}
male[51:68,] %>% 
  knitr::kable(booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  add_indent(c(4, 6, 9, 13))
```

### PAR Table Total Adjusted for Age and Sex (ntotal = 2070371, nfall = 31244)

```{r, include = FALSE}
adjusted = read_csv("./adjusted_combined.csv")
```

```{r, echo = FALSE}
adjusted %>% 
  knitr::kable(booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  add_indent(c(2, 3, 5, 7, 9, 11:14, 16, 17, 19, 20, 22, 
               25, 27, 29, 30, 33, 36, 37, 39, 42, 44, 47))
```



