---
title: "Network Graph of Injury-Disease Interactions"
author: "Adina Zhang"
date: "May 27, 2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(igraph)
```

```{r, include = FALSE}
# ICD 10 hierarchy data
icd10_df = read_csv("icd10_hierarchy.csv") %>% 
  rename(id = three_digit)

# Assign edge data
edge1 = read_csv("pairs_3digits.csv") %>% 
  rename(from = Var1, to = Var2) %>% 
  select(from, to, Obs, Exp, PMR, PAR)

edge2 =  read_csv("edge_data.csv") %>% select(-major) %>% 
  mutate(from = "W00-W19",
         to = ICD10) %>% 
  select(from, to, Obs, Exp, PMR, PAR) %>% 
  filter(to %in% edge1$to | to %in% edge1$from | PAR > 0.1)

edge = rbind(edge1, edge2)

# Assign node data (create a better dataset that captures all the distinct nodes and prevalence data)
node1 = distinct(edge, to) %>% rename(id = to)
node2 = distinct(edge, from) %>% rename(id = from)
node3 = rbind(node1, node2) %>% distinct(id)
icd10_df = icd10_df %>% filter(id %in% node3$id) 
node = full_join(node3, icd10_df, by = "id") %>% distinct(id, major, chapter)
```


```{r, echo = FALSE}
library(visNetwork)

# Define node and edge variables
vis.nodes = node
vis.links = edge

# Adjust node settings
vis.nodes$label = vis.nodes$id
vis.nodes$title = vis.nodes$major

# Adjust edge settings
vis.links$title = paste(edge$from, " and ", edge$to, ", 
                        PAR = ", edge$PAR, ", PMR = ", edge$PMR)
vis.links$width = 1 + edge$PAR/8
vis.links$color = "gray"

# Plot network diagram
visNetwork(vis.nodes, vis.links) 
```

```{r, echo = FALSE}
# Define node and edge variables
vis.nodes = node
vis.links = edge

# Adjust node settings
vis.nodes$label = vis.nodes$id
vis.nodes$title = vis.nodes$major

# Adjust edge settings
vis.links$title = paste(edge$from, " and ", edge$to, ", 
                        PAR = ", edge$PAR, ", PMR = ", edge$PMR)
vis.links$width = 1 + edge$PAR/8

# Plot circular network diagram
visNetwork(vis.nodes, vis.links) %>% 
  visIgraphLayout(layout = "layout_as_star") %>% 
  visNodes(size = 10) %>% 
  visOptions(highlightNearest = list(enabled = T, hover = T), 
             nodesIdSelection = T)
```


