---
title: "PMR Tables, Age and Sex Adjusted with Four ICD10 Digits"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

```{r, cache = TRUE, include = FALSE}
# Load datasets
mort65plus = read_csv("../mort17_65plus.csv")
icd10_data = read_csv("../icd10_hierarchy.csv")
```

```{r, include = FALSE}
# Create age and sex adjusted tables
# New age group
mort65plus = mort65plus %>% 
  filter(age_value < 120) %>% 
  mutate(age_grp = cut(age_value, 
                       c(65, 70, 75, 80, 85, 90, 120), 
                       right = FALSE))

age_sex = mort65plus %>% 
  select(age_grp, sex, icd10, ra2:ra20)
```

```{r, include = FALSE}
# Create functions from previous code to apply across each dataset
# Function that filters for falls dataset
falls_death = function(data){
  data %>% 
    filter(grepl("W", icd10)) %>%
    mutate(number = str_sub(icd10, 2, 3)) %>% 
    filter(number <= 19) %>% # Not all W's are fall-related, just W00-W19
    select(-number)
}

# Function to specify which icd10code we are using
# Yields an icd10 code dataset
icd10_select = function(...){
  if (... == "icd10code"){
    icd10_data %>% 
      select(icd10code, short_desc)
  }
  else if (... == "three digit"){
    icd10_data %>% 
      select(icd10code, three_digit, major)
  }
  else {
    icd10_data %>% 
      select(icd10code, sub_chapter_group, sub_chapter)
  }
}

# Function to turn falls dataframe into a "tidy" version
# Join tidy version with icd10 dataset by icd10code (for aggregating)
tidy = function(data, icd10_df){
  data = data %>% 
    gather(key = ra_position, value = icd10code, ra2:ra20)
  full_join(data, icd10_df, by = "icd10code")
}

# Function to count icd10 values for overall group
count_grp = function(data, ...){
  data = data %>% 
    gather(key = ra_position, value = icd10code, ra2:ra20) %>% 
    na.omit()
  data1 = full_join(data, icd10_df, by = "icd10code") %>% 
    group_by(...) %>% 
    summarize(n = n())
  names(data1)[1] = "icd10"
  return(data1)
}
  
# Function to count icd10 values for those with falls
count_fall = function(data, ...){
  data = data %>% 
    na.omit() %>% 
    group_by(...) %>%
    summarize(obs = n())
  names(data)[1] = "icd10"
  return(data)
}

# Function to count observed and expected values
pmr_count = function(count1, count2, data, fall){
  full_join(count1, count2, by = "icd10") %>% 
    mutate(prev = n / dim(data)[1],
         prev_fall = obs / dim(fall)[1],
         expect = round(prev * dim(fall)[1], digits = 2)) %>% 
    na.omit()
}

aggregate = function(data){
  # Unnest nested data and aggregate across obs and expected values
  summary = data %>% unnest(summary)
  count = data %>% 
    unnest(count) %>% 
    group_by(icd10) %>% 
    summarize(n = sum(n))
  my_list = list(summary, count)
  return(my_list)
}

par = function(summary, count, nfall, ntotal){
  # Calculate PMR ------------------------------------------------------ 
  temp = summary %>% 
    group_by(icd10, nfall , ntotal) %>% 
    summarize(obs = sum(obs),
              exp = sum(expect)) %>% 
    mutate(pmr = round(obs/exp, digits = 2),
           se_pmr = round(sqrt(obs)/exp, digits = 2),
           l95_pmr = round(pmr - 1.96 * se_pmr, digits = 2),
           u95_pmr = round(pmr + 1.96 * se_pmr, digits = 2)) %>% 
    filter(!str_detect(icd10, "^S"),
           !str_detect(icd10, "^T0"),
           !str_detect(icd10, "^T1"))
  # Calculate PAR ------------------------------------------------------
  full_join(count, temp, by = "icd10") %>% 
    na.omit() %>% 
    mutate(prev = n/ntotal,
           par = round(100 * ((prev * (pmr - 1)) / 
                              (prev * (pmr - 1) + 1)), digits = 2)) %>%
    arrange(desc(par))
}

# Function to tidy up the summary
clean_summary = function(data, icd10_data){
  if (dim(icd10_data)[2] > 2) {
    names(icd10_data)[2] = "icd10"
    icd10_data = icd10_data %>% 
      select(-icd10code) %>% 
      distinct()
  } else {
    names(icd10_data)[1] = "icd10"
  }
  data = data %>% 
    select(icd10, obs, exp, pmr, l95_pmr, u95_pmr, par)
  full_join(data, icd10_data, by = "icd10") %>%
    filter(!is.na(pmr)) %>% 
    unite(PMR_95CI, l95_pmr, u95_pmr, sep = ", ") %>%
    mutate(PMR_95CI = paste0("(", PMR_95CI, ")")) %>% 
    rename(ICD10 = icd10,
           Obs = obs,
           Exp = exp,
           PMR = pmr,
           PAR = par)
}
```

```{r, include = FALSE}
# Select icd10 code to aggregate by
icd10_df = icd10_select("three digit")

# Nest data by age_grp and sex
age_sex_nest = nest(age_sex, icd10:ra20)

# Apply all functions to the nested dataframes
# Create tables that summarize PMR for each age-sex group
age_sex_nest = age_sex_nest %>% 
  mutate(falls = map(.x = data, ~falls_death(.x))) %>% 
  mutate(tidy = map(.x = falls, ~tidy(.x, icd10_df))) %>% 
  mutate(count = map(.x = data, ~count_grp(.x, three_digit)),
         count_fall = map(.x = tidy, ~count_fall(.x, three_digit))) %>% 
  mutate(summary = pmap(list(count, count_fall, data, falls ), pmr_count)) 
```

```{r, include = FALSE}
# Adjust for females
female = age_sex_nest %>% 
  filter(sex == "F") %>% 
  mutate(ntotal = map(.x = data, ~dim(.x)[1]),
         nfall = map(.x = falls, ~dim(.x)[1])) %>% 
  mutate(ntotal = Reduce("+", ntotal),
         nfall = Reduce("+", nfall))
```

### Adjusted for Females (ntotal = `r female$ntotal[1]`, nfalls = `r female$nfall[1]`)

```{r, echo = FALSE}
fem_agg = female %>% aggregate()
female =  par(fem_agg[[1]], fem_agg[[2]]) %>% 
  clean_summary(.,icd10_df) %>% 
  filter(PAR >= 0.1, PMR > 1.5) 

female %>% knitr::kable(booktabs = T) %>% 
    kable_styling(latex_options = c("striped", "scale_down"))
```

\newpage 

```{r, include = FALSE}
# Adjust for Males
male = age_sex_nest %>% 
  filter(sex == "M") %>% 
  mutate(ntotal = map(.x = data, ~dim(.x)[1]),
         nfall = map(.x = falls, ~dim(.x)[1])) %>% 
  mutate(ntotal = Reduce("+", ntotal),
         nfall = Reduce("+", nfall))
```

### Adjusted for Males (ntotal = `r male$ntotal[1]`, nfalls = `r male$nfall[1]`)

```{r, echo = FALSE}
male_agg = male %>% aggregate()
male =  par(male_agg[[1]], male_agg[[2]]) %>% 
  clean_summary(.,icd10_df) %>% 
  filter(PAR >= 0.1, PMR > 1.5)

male %>% knitr::kable(booktabs = T) %>% 
    kable_styling(latex_options = c("striped", "scale_down"))
```

\newpage

### Age and Sex Adjusted

```{r, include = FALSE}
# Calculate ntotal and nfall for adjusting age and sex
age_sex_adjusted = age_sex_nest %>% 
  mutate(ntotal = map(.x = data, ~dim(.x)[1]),
         nfall = map(.x = falls, ~dim(.x)[1])) %>% 
  mutate(ntotal = Reduce("+", ntotal),
         nfall = Reduce("+", nfall))

# Adjust for age and sex
adj_agg = age_sex_adjusted %>% aggregate()
age_sex_adjusted = par(adj_agg[[1]], adj_agg[[2]]) %>% 
  clean_summary(., icd10_df) %>% 
  filter(PAR >= 0.1, PMR > 1.5)
```

```{r, echo = FALSE}
age_sex_adjusted %>% knitr::kable(booktabs = T) %>% 
    kable_styling(latex_options = c("striped", "scale_down"))
```

\newpage

### Table 1. Characteristics of sample population

```{r}
# Initialize empty table 1
table1 = tibble()

# Summarize age groups by gender
age_summary = age_sex %>% 
  group_by(sex, age_grp) %>% 
  summarize(n = n()) %>% 
  spread(key = sex, value = n)
age_summary = age_summary %>% 
  mutate(`F%` = (age_summary$F / dim(mort65plus)[1]) * 100,
         `M%` = (age_summary$M / dim(mort65plus)[1]) * 100)

race_summary = mort65plus %>% 
  group_by(sex, race_recode_5) %>% 
  summarize(n = n()) %>% 
  spread(key = sex, value = n) %>% 
  mutate(race_recode_5 = factor(race_recode_5)) %>% 
  mutate(race_recode_5 = fct_recode(race_recode_5,
                                    "Other" = "0",
                                    "White" = "1",
                                    "Black" = "2",
                                    "American Indian" = "3",
                                    "Asian" = "4"))


```


\newpage

### Male vs. Female Dot Plot

```{r, echo = FALSE}
female1 = female %>% 
  mutate(sex = "F")

male1 = male %>% 
  mutate(sex = "M")

plot1 = rbind(female1, male1)

big_diff = plot1 %>% 
  select(ICD10, PAR, sex) %>% 
  spread(sex, PAR) %>% 
  group_by(ICD10) %>% 
  mutate(Max = max(F, M),
         Min = min(F, M),
         Diff = Max / Min - 1) %>% 
  arrange(desc(Diff)) %>% 
  na.omit() 

test = big_diff %>% 
  select(-Max, -Min) %>% 
  gather(key = sex, value = PAR, F:M)
  
test %>% ggplot(aes(PAR, reorder(ICD10, PAR))) + 
  geom_line(aes(group = ICD10)) + 
  geom_point(aes(color = sex)) + 
  labs(title = "Total PAR by ICD10 and Gender",
       y = "ICD10") + 
  theme_minimal()
```

```{r, echo = FALSE}
big_diff = plot1 %>% 
  select(ICD10, PMR, sex) %>% 
  spread(sex, PMR) %>% 
  group_by(ICD10) %>% 
  mutate(Max = max(F, M),
         Min = min(F, M),
         Diff = Max / Min - 1) %>% 
  arrange(desc(Diff)) %>% 
  na.omit() 

test = big_diff %>% 
  select(-Max, -Min) %>% 
  gather(key = sex, value = PMR, F:M)
  
test %>% ggplot(aes(PMR, reorder(ICD10, PMR))) + 
  geom_line(aes(group = ICD10)) + 
  geom_point(aes(color = sex)) + 
  labs(title = "Total PMR by ICD10 and Gender",
       y = "ICD10") + 
  theme_minimal()
```

\newpage

### Plot PAR differences over age groups

```{r, include = FALSE}
# Select top ICD10 in age 65-69 age group
y65 = age_sex_nest %>% 
  filter(age_grp == "[65,70)") %>% 
  mutate(ntotal = map(.x = data, ~dim(.x)[1]),
         nfall = map(.x = falls, ~dim(.x)[1])) %>% 
  mutate(ntotal = Reduce("+", ntotal),
         nfall = Reduce("+", nfall))

y65_agg = y65 %>% aggregate()
y65 =  par(y65_agg[[1]], y65_agg[[2]]) %>% 
  clean_summary(.,icd10_df) %>% 
  filter(PAR >= 0.1, PMR > 1.5) 

top10_y65 = top_n(y65, 10, PAR)

# Select top ICD10 in age 90+ age group
y90 = age_sex_nest %>% 
  filter(age_grp == "[90,120)") %>% 
  mutate(ntotal = map(.x = data, ~dim(.x)[1]),
         nfall = map(.x = falls, ~dim(.x)[1])) %>% 
  mutate(ntotal = Reduce("+", ntotal),
         nfall = Reduce("+", nfall))

y90_agg = y90 %>% aggregate()
y90 =  par(y90_agg[[1]], y90_agg[[2]]) %>% 
  clean_summary(.,icd10_df) %>% 
  filter(PAR >= 0.1, PMR > 1.5) 

top10_y90 = top_n(y90, 10, PAR)

# Join top 10 from both age groups into one reference dataframes
top10 = rbind(top10_y65, top10_y90) %>% 
  distinct(ICD10)
```

```{r, echo = FALSE, message = FALSE, error = FALSE, warning = FALSE}
# Prepare dataset for plotting
age_plot = age_sex_nest %>% 
  mutate(ntotal = map(.x = data, ~dim(.x)[1]),
         nfall = map(.x = falls, ~dim(.x)[1])) %>% 
  mutate(summary = map2(summary, ntotal, ~mutate(.x, ntotal = .y)),
         summary = map2(summary, nfall, ~mutate(.x, nfall = .y))) %>% 
  mutate(summary = pmap(list(summary, count, nfall, ntotal), par)) %>% 
  unnest(summary) %>% 
  mutate(par = ifelse(par < 0, 0, par))

# Add missing point for R54 in 65-69 age group among females
age_plot = age_plot %>% 
  add_row(age_grp = "[65,70)", sex = "F", icd10 = "R54", par = 0) 

# Select rows which only have an icd10 code that is in the top 15 codes previously identified
plot2 = tibble()
for (i in 1:dim(age_plot)) {
  for (j in 1:dim(top10)){
    if (age_plot$icd10[i] == top10$ICD10[j]) {
      plot2 = rbind(plot2, age_plot[i,])
      }
  }
}

# Combine alcohol related disorders into one icd10
# Combine obs, exp, and n values to yield new PAR
alc_combo = plot2 %>% 
  filter(icd10 %in% c("F10", "X45", "T51", "K70")) %>% 
  group_by(age_grp, sex, ntotal) %>% 
  summarize(n = sum(n), obs = sum(obs), exp = sum(exp)) %>% 
  mutate(pmr = obs/exp,
         prev = n/ntotal,
         par = (prev * (pmr - 1)) / (prev * (pmr - 1) + 1),
         par = round(100 * par, digits = 2),
         par = replace_na(par, 0),
         icd10 = "F10, X45, T51, K70") 

# Remove alcohol specific icd10 codes and join the combined alcohol icd10 dataframe to the plotting dataset
temp = plot2 %>% filter(!icd10 %in% c("F10", "X45", "T51", "K70"))
plot2 = bind_rows(temp, alc_combo)
```

```{r, echo = FALSE, warning = FALSE}
library(ggrepel)
p = plot2 %>% 
  mutate(label = ifelse(age_grp == "[90,120)", icd10, NA_character_),
         age_grp = fct_recode(age_grp,
                              "65-69" = "[65,70)",
                              "70-74" = "[70,75)",
                              "75-79" = "[75,80)",
                              "80-84" = "[80,85)",
                              "85-89" = "[85,90)",
                              "90+" = "[90,120)"),
         sex = fct_recode(sex, "Male" = "M", "Female" = "F"),
         sex = fct_relevel(sex, levels = c("Male", "Female"))) %>% 
  ggplot(aes(x = age_grp, y = par)) +
  geom_line(aes(group = icd10, color = icd10)) + 
  facet_grid(.~sex) + 
  labs(title = "Population attributable risk (PAR) of comorbid conditions associated with deaths from falls in adults 65+ years by sex in 2017",
       x = "Age Group (Years)",
       y = "Population Attributable Risk (PAR)") +
  geom_text_repel(aes(x = age_grp, y = par, label = label, color = icd10),
                  show.legend = FALSE, size = 5) + 
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12)) + 
  scale_color_manual(values = c("#374E55FF", "#DF8F44FF","#00A1D5FF", 
                                "#B24745FF", "#79AF97FF", "#6A6599FF",
                                "#80796BFF", "#374E5599", "#DF8F4499",
                                "#00A1D599", "#B2474599", "#6A659999"),
                     name = "Disease", 
                     labels = c("Diabetes Mellitus, unspecified (E14)",
                                "Dementia, unspecified (F03)", 
                                "Alcohol Related Disorders, Disease, 
                                        or Exposure  (F10, X45, T51, K70)", 
                                 "Parkinson's Disease (G20)", 
                                 "Alzheimer's Disease (G30)",
                                 "Hypertensive Heart Disease (I11)",
                                 "Chronic Ischemic Heart Disease (I25)",
                                 "Pulmonary Embolism (I26)",
                                 "Other Chronic Obstructive Pulmonary Disease (J44)",
                                 "Osteoporosis (M81)",
                                 "Abnormalities of Gait and Mobility (R26)",
                                 "Age-related Physical Disability (R54)")) +
  theme_minimal() + 
  theme(legend.position = "bottom",
        strip.text.x = element_text(size = 13, face = "bold"),
        axis.text = element_text(size = 13),
        axis.title = element_text(size = 13,face = "bold"),
        plot.title = element_text(size = 14)) 

```


